name: Deploy to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.HOSTGATOR_SSH_KEY }}

      - name: Deploy to HostGator
        env:
          HOSTGATOR_USER: ${{ secrets.HOSTGATOR_USERNAME }}
          HOSTGATOR_HOST: ${{ secrets.HOSTGATOR_HOST }}
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" / $HOSTGATOR_USER@$HOSTGATOR_HOST:/home/billionapps/public_html/chat.billionapps.net/devchat/
